project:
  type: website
  output-dir: docs
  resources:
    - pages/

website:
  title: "Clash Royale Matchmaking Analysis"
  search: true
  navbar:
    title: false
    background: primary
    left:
      - href: pages/index.qmd
        text: Executive summary
        icon: house
      - href: pages/01_match_scraping.qmd
        text: "Match scraping"
        icon: database
      - href: pages/02_matchmaking_analysis.qmd
        text: "Matchmaking analysis"
        icon: bar-chart-line
    right:
      - icon: github
        href: https://github.com/CrabGuy/ClashRoyaleMatchmakingAnalysis

format:
  html:
    theme: flatly
    toc: true
    code-fold: show
    format-links: false
  ipynb: default

execute:
  freeze: auto